before:
  hooks:
    - go mod download
builds:
  - id: coredns
    main: ./cmd/coredns/main.go
    binary: coredns
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64

  - id: wgsd-client
    main: ./cmd/wgsd-client/main.go
    binary: wgsd-client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64

archives:
  - id: coredns
    format: tar.gz
    name_template: wgsd-coredns_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    builds:
      - coredns

  - id: wgsd-client
    format: tar.gz
    name_template: wgsd-client_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    builds:
      - wgsd-client
